# Лабораторная работа №4.
# Анализ данных пассажиров "Титаника"

Гибель Титаника – одно из самых печально известных кораблекрушений в истории.

15 апреля 1912 года во время своего первого плавания считавшийся «непотопляемым» «Титаник» затонул после столкновения с айсбергом.
К сожалению, спасательных шлюпок для всех находившихся на борту не хватило, в результате чего погибли 1502 из 2224 пассажиров и членов экипажа.

Используя набор данных titanic.csv выполните следующие 10 заданий.

In [1]:
import numpy as np
import pandas as pd

1. Создайте DataFarame из файла titanic.csv, в качестве индекса используйте столбец "PassengerId"

In [4]:
import numpy as np
import pandas as pd
titanic_df = pd.read_csv("titanic.csv", index_col='PassengerId')
titanic_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

2. Просмотрите первые 6 строк

In [5]:
import numpy as np
import pandas as pd
titanic_df = pd.read_csv("titanic.csv", delimiter=',')
titanic_df[:6]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

3. Выведите описание данных

In [6]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

4. Сколько мужчин / женщин находилось на борту?

In [7]:
titanic_df.groupby('Sex').count()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
female,314,314,314,314,261,314,314,314,314,97,312
male,577,577,577,577,453,577,577,577,577,107,577

4. Выведите распределение переменной Pclass (социально-экономический статус) и это же распределение, только для мужчин / женщин по отдельности. Сколько было мужчин 2-го класса

In [13]:
df = pd.read_csv('titanic.csv')
print("Общее распределение по классам (Pclass):")
print(df['Pclass'].value_counts().sort_index())
print("-" * 30)

print("Распределение по классам в разрезе пола:")
distribution_by_sex = df.groupby(['Sex', 'Pclass']).size().unstack(fill_value=0)
distribution_by_sex = distribution_by_sex[[1, 2, 3]]
print(distribution_by_sex)
print("-" * 30)

men_2nd_class = df[(df['Sex'] == 'male') & (df['Pclass'] == 2)].shape[0]

print(f"Количество мужчин 2-го класса: {men_2nd_class}")

Общее распределение по классам (Pclass):
Pclass
1    216
2    184
3    491
Name: count, dtype: int64
------------------------------
Распределение по классам в разрезе пола:
Pclass    1    2    3
Sex
female   94   76  144
male    122  108  347
------------------------------
Количество мужчин 2-го класса: 108

5. Каковы медиана и среднеквадрати́чное отклонение платежей (Fare)? Округлите до 2 десятичных знаков.

In [14]:
median = round(titanic_df['Fare'].median(), 2)
std = round(titanic_df['Fare'].std(), 2)
print("Медиана:", median)
print("Среднеквадрати́чное отклонение:", std)

Медиана: 14.45
Среднеквадрати́чное отклонение: 49.69

6. Правда ли, что люди моложе 30 лет выживали чаще, чем люди старше 60 лет? Каковы доли выживших в обеих группах?

In [16]:
younger = titanic_df[titanic_df['Age'] < 30]
older = titanic_df[titanic_df['Age'] > 60]
ysurvived = round(younger['Survived'].mean(), 2)
osurvived = round(older['Survived'].mean(), 2)
print("Доля выживанания людей моложе 30 лет:", ysurvived)
print("Доля выживания людей старше 60 лет:", osurvived)
print("Люди моложе 30 лет выживали чаще") if ysurvived > osurvived else print("Данное утверждение неверно")

Доля выживанания людей моложе 30 лет: 0.41
Доля выживания людей старше 60 лет: 0.23
Люди моложе 30 лет выживали чаще

7. Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших в обеих группах?

In [18]:
male = titanic_df[titanic_df['Sex'] == "male"]
female = titanic_df[titanic_df['Sex'] == "female"]
msurvived = round(male['Survived'].mean(), 3)
fsurvived = round(female['Survived'].mean(), 3)
print("Доля выживания мужчин:", msurvived)
print("Доля выживания женщин:", fsurvived)
print("Женщины выживали чаще мужчин") if fsurvived > msurvived else print("Данное утверждение неверно")

Доля выживания мужчин: 0.189
Доля выживания женщин: 0.742
Женщины выживали чаще мужчин

8.  Найдите самое популярное имя среди пассажиров Титаника мужского пола?

In [20]:
import re
from collections import Counter

df = pd.read_csv('titanic.csv')

men_df = df[df['Sex'] == 'male']

def extract_name(full_name):
    try:
        part_after_comma = full_name.split(',')[1]
        words = part_after_comma.strip().split()

        for word in words:
            clean_word = word.replace('.', '')
            if clean_word not in ['Mr', 'Master', 'Dr', 'Rev', 'Col', 'Major', 'Sir', 'Jonkheer']:
                return clean_word
    except IndexError:
        return None

men_df['FirstName'] = men_df['Name'].apply(extract_name)

name_counts = Counter(men_df['FirstName'])
most_common_name, count = name_counts.most_common(1)[0]

print(f"Самое популярное имя среди мужчин: {most_common_name}")
print(f"Количество повторений: {count}")
print("\nТоп-5 популярных имен:")
for name, count in name_counts.most_common(5):
    print(f"{name}: {count}")

Самое популярное имя среди мужчин: William
Количество повторений: 35

Топ-5 популярных имен:
William: 35
John: 25
George: 14
Charles: 13
Thomas: 13

/tmp/ipykernel_819/2059864869.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  men_df['FirstName'] = men_df['Name'].apply(extract_name)



9. Как отличается средний возраст мужчин / женщин в зависимости от класса обслуживания? Выберите верные утверждения:

    В среднем мужчины 1-го класса старше 40 лет
    В среднем женщины 1-го класса старше 40 лет
    Мужчины всех классов в среднем старше женщин того же класса
    В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса

In [21]:
mean_age = titanic_df.groupby(['Pclass', 'Sex'])['Age'].mean()
print(mean_age)

men_first_class = titanic_df[(titanic_df['Pclass'] == 1) & (titanic_df['Sex'] == 'male')]
women_first_class = titanic_df[(titanic_df['Pclass'] == 1) & (titanic_df['Sex'] == 'female')]

men_second_class = titanic_df[(titanic_df['Pclass'] == 2) & (titanic_df['Sex'] == 'male')]
women_second_class = titanic_df[(titanic_df['Pclass'] == 2) & (titanic_df['Sex'] == 'female')]

men_third_class = titanic_df[(titanic_df['Pclass'] == 3) & (titanic_df['Sex'] == 'male')]
women_third_class = titanic_df[(titanic_df['Pclass'] == 3) & (titanic_df['Sex'] == 'female')]


men_first_class_age = round(men_first_class['Age'].mean(), 2)
women_first_class_age = round(women_first_class['Age'].mean(), 2)

men_second_class_age = round(men_second_class['Age'].mean(), 2)
women_second_class_age = round(women_second_class['Age'].mean(), 2)

men_third_class_age = round(men_third_class['Age'].mean(), 2)
women_third_class_age = round(women_third_class['Age'].mean(), 2)


print("\nАнализ утверждений:")


print("1. В среднем мужчины 1-го класса старше 40 лет:", "Верно!" if men_first_class_age > 40 else "Неверно!")


print("2. В среднем женщины 1-го класса старше 40 лет:", "Верно!" if women_first_class_age > 40 else "Неверно!")


men_older_women = (
    men_first_class_age > women_first_class_age and
    men_second_class_age > women_second_class_age and
    men_third_class_age > women_third_class_age
)

print("3. Мужчины всех классов в среднем старше женщин того же класса:", "Верно!" if men_older_women else "Неверно!")


first_class_older = (men_first_class_age > men_second_class_age > men_third_class_age and
                     women_first_class_age > women_second_class_age > women_third_class_age)
print("4. В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса:", "Верно!" if first_class_older else "Неверно!")

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

Анализ утверждений:
1. В среднем мужчины 1-го класса старше 40 лет: Верно!
2. В среднем женщины 1-го класса старше 40 лет: Неверно!
3. Мужчины всех классов в среднем старше женщин того же класса: Верно!
4. В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса: Верно!

10. Сравните возраст у спасенных и у погибших пасажиров. Средний возраст погибших выше, верно?

In [22]:
survived = titanic_df[titanic_df['Survived'] == 1]
dead = titanic_df[titanic_df['Survived'] == 0]
survived_age = round(survived['Age'].mean(), 2)
dead_age = round(dead['Age'].mean(), 2)
print("Возраст спасенных пасажиров:", survived_age)
print("Возраст погибших пасажиров:", dead_age)
print("Средний возраст погибших выше") if dead_age > survived_age else print("Утверждение неверно")

Возраст спасенных пасажиров: 28.34
Возраст погибших пасажиров: 30.63
Средний возраст погибших выше!

### Дополнительные вопросы для защиты

1. Что такое медиана? Рассчитать медиану для предложенного ряда чисел.
```
Медиана — это значение, которое делит упорядоченный ряд чисел ровно пополам:
половина значений меньше медианы, половина — больше. Если количество чисел
нечетное, медиана равна центральному элементу. Если четное — среднему
арифметическому двух центральных элементов.
```
2. Что такое дисперсия? Рассчитать дисперсию для предложенного ряда чисел.
```
Дисперсия — это мера разброса данных, показывающая, насколько сильно значения
отклоняются от их среднего арифметического. Формально это средний квадрат
отклонений значений от их математического ожидания. Чем выше дисперсия, тем
больше разброс данных.
```
3. Что такое среднеквадратичное отклонение? Рассчитать среднеквадратичное отклонение для предложенного ряда чисел.
```
Среднеквадратичное отклонение (СКО или стандартное отклонение) — это корень
квадратный из дисперсии. Оно измеряет разброс данных в тех же единицах
измерения, что и исходные данные (в отличие от дисперсии, где единицы возведены
в квадрат). Это наиболее популярная мера изменчивости.
```
4. Что такое Series и чем он отличается от DataFrame
```
Что такое Series и чем он отличается от DataFrame?
Series в pandas — это одномерный массив данных с подписанными индексами
(метками). По сути, это один столбец таблицы.
DataFrame — это двумерная таблица данных (строки и столбцы), где каждый столбец
является объектом Series.
Главное отличие: Series хранит одну последовательность значений (один признак),
а DataFrame — коллекцию таких последовательностей, объединенных общими
индексами (множество признаков).
```
5. Можно ли изменить индекс в Series после создания объекта?
```
Можно ли изменить индекс в Series после создания объекта?
Да, можно. Индекс — это изменяемый атрибут. Присвоить новый индекс можно
напрямую через свойство .index (например, series.index = new_index) или
используя метод .set_axis(). Также можно создать копию с новым индексом через .
rename().
```
6. Можно ли выполнить операцию сложения над двумя объектами Series, если они имеют:
- одинаковые типы данных, одинаковые размеры и одинаковые индексы?
- одинаковые типы данных, одинаковые размеры, но разные индексы?,  
- одинаковые типы данных, разные размеры и одинаковые индексы?
- разные типы данных, одинаковые размеры и одинаковые индексы?
- разные типы данных, одинаковые размеры и разные индексы?
- разные типы данных, разные размеры и разные индексы?
```
Можно ли выполнить операцию сложения над двумя объектами Series...

Операция сложения в pandas выполняется по индексам (выравнивание), а не просто
по позициям.

Одинаковые типы, размеры и индексы: Да, сложится поэлементно. Результат будет
корректным Series той же длины.

Одинаковые типы, размеры, но разные индексы: Да, выполнится, но результат будет
содержать NaN там, где индексы не совпали. Если индексы полностью различны,
результат будет состоять только из NaN (длина суммы уникальных индексов).

Одинаковые типы, разные размеры, одинаковые индексы: Технически невозможно
иметь "одинаковые индексы" при разных размерах, если под этим подразумевается
полный набор меток. Если один индекс является подмножеством другого, сложение
пройдет по пересекающимся меткам, а для отсутствующих в меньшем Series будут
NaN.

Разные типы данных, одинаковые размеры и индексы: Да, если типы совместимы
(например, int и float). pandas попытается привести типы к общему (обычно к
более широкому, например, float). Если типы несовместимы (например, string и
int без явного преобразования), возникнет ошибка.

Разные типы, размеры и индексы: Выполнится попытка сложения по пересекающимся
индексам с приведением типов. Результат скорее всего будет содержать много NaN
и может иметь тип object или float, в зависимости от данных.

Разные типы, размеры и индексы (полностью несовпадающие): Операция выполнится,
но результат будет Series, заполненный NaN, так как пересечения индексов нет.
Тип данных результата зависит от логики приведения типов pandas для операндов.
```
7. Что такое DataFrame и чем он отличается от Series
```
Series в pandas — это одномерный массив данных с подписанными индексами
(метками). По сути, это один столбец таблицы.
DataFrame — это двумерная таблица данных (строки и столбцы), где каждый столбец
является объектом Series.
Главное отличие: Series хранит одну последовательность значений (один признак),
а DataFrame — коллекцию таких последовательностей, объединенных общими
индексами (множество признаков).
```
8. Что необходимо сделать, чтобы число строк в DateFrame при его просмотре, по умолчанию составляло 8?
```
Нужно изменить настройку отображения pandas через функцию pd.set_option.
Команда: pd.set_option('display.max_rows', 8).
После этого при выводе DataFrame в консоль будет показываться не более 8 строк
(с усечением середины, если строк больше).
```
9. Чем отличается метод iloc от метода loс
```
loc (location) работает с метками индексов и именами столбцов. Срезы включают
правую границу (например, loc[1:5] включит строки с индексами 1, 2, 3, 4, 5).
iloc (integer location) работает с целочисленными позициями (как в обычных
списках Python). Срезы не включают правую границу (например, iloc[1:5] включит
строки с позициями 1, 2, 3, 4).
```
10. Можно ли добавить в DateFrame дополнительный Series?
```
Да, можно. Если присвоить новый Series существующему DataFrame как новый
столбец (например, df['new_col'] = series), pandas автоматически выровняет
данные по индексам. Если индексы Series совпадают с индексами DataFrame, данные
встанут корректно. Если не совпадают — появятся NaN.
```
11. Требуются ли установка дополнительных библиотек для загрузки с помощью pandas файлов в формате CSV? Excel (.xls)? Json?
```
CSV: Нет, поддержка встроена в сам pandas (использует встроенные возможности
Python).
JSON: Нет, поддержка также встроена в pandas (использует стандартный модуль
json или ujson, если установлен, но не обязателен).
Excel (.xls, .xlsx): Да, требуются дополнительные библиотеки. Для чтения
современных файлов (.xlsx) обычно нужен openpyxl или odfpy, для старых (.xls) —
xlrd. Без них вызов pd.read_excel() выдаст ошибку ImportError.
```